# Generated by Django 3.2.8 on 2021-12-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_beneficiary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postadmin',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='suco',
            name='postadmin',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='postadmin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='suco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='PostAdmin',
        ),
        migrations.DeleteModel(
            name='Suco',
        ),
    ]
