# Generated by Django 3.2.8 on 2022-02-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_municipality_postadmin_suco'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
