# Generated by Django 3.2.8 on 2022-03-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_beneficiary__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='_id',
            new_name='bene_id',
        ),
    ]
