"""
Django settings for django_api_enpoint project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x%qfrrl@p5^nu33kq+qb@_6n9qki+#43j4rjqg&5l7kjm1^aie'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
]

# django_kobocollect/django_api_enpoint/django_api_enpoint/settings.py
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.NoCacheAPIMiddleware',  # Prevent API response caching
]

ROOT_URLCONF = 'django_api_enpoint.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_api_enpoint.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kobo_db',
        'HOST': '127.0.0.1',
        'PORT': 5433,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dili'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "dist"),
]

LOGIN_REDIRECT_URL = '/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# Enketo Express Configuration
# ============================================================================
# Enketo Express service URL
# Set this environment variable to enable Enketo integration
# Example: export ENKETO_URL=http://localhost:8005
# For production: export ENKETO_URL=https://enketo.yourdomain.com
# If not set, Enketo integration will be disabled
ENKETO_URL = os.getenv('ENKETO_URL', 'http://localhost:8005')

# Enketo Express API token for authentication
# Optional but recommended for production use
# Get this from your Enketo Express installation
# Example: export ENKETO_API_TOKEN=your_api_token_here
ENKETO_API_TOKEN = os.getenv('ENKETO_API_TOKEN', 'dev_token_12345')

# Request timeout for Enketo API calls (in seconds)
ENKETO_REQUEST_TIMEOUT = int(os.getenv('ENKETO_REQUEST_TIMEOUT', '30'))

# Site URL for building return URLs (used in form rendering)
# If not set, will attempt to use request.get_host()
# Example: export SITE_URL=http://localhost:8000
SITE_URL = os.getenv('SITE_URL', '')

# ============================================================================
# Kobo Toolbox Configuration
# ============================================================================
# Kobo API base URL
# Default: https://kf.kobotoolbox.org/api/v2 (Kobo Toolbox)
# Alternative: https://kobo.humanitarianresponse.info/api/v2 (Kobo Humanitarian Response)
KOBO_API_BASE_URL = os.getenv('KOBO_API_BASE_URL', 'https://kf.kobotoolbox.org/api/v2')

# Kobo API access token (legacy setting - used by KoboService)
ACCESS_TOKEN = os.getenv('ACCESS_TOKEN', '571af44fa0751fed351e79fdac553f7dd89f2c5c')

# Default Kobo asset ID for data fetching
KOBO_DEFAULT_ASSET_ID = os.getenv('KOBO_DEFAULT_ASSET_ID', 'awVr5i22y9sWTYd5KguiGr')

# Request timeout for Kobo API calls (in seconds)
KOBO_REQUEST_TIMEOUT = int(os.getenv('KOBO_REQUEST_TIMEOUT', '30'))

# ============================================================================
# Configuration Validation
# ============================================================================
# Validate Enketo configuration on startup (in development)
if DEBUG:
    if not ENKETO_URL:
        import warnings
        warnings.warn(
            'ENKETO_URL is not configured. Enketo integration will not work properly.',
            UserWarning
        )
